imports:
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  en
#    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        cookie_domain: %site_domain%
        name: webosess
        save_path: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - '::form/main.html.twig'
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver: 'pdo_mysql'
        charset:  'UTF8'
        server_version: '5.6'
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

#Doctrine MongoDB
doctrine_mongodb:
    connections:
        default:
            server: '%env(MONGODB_SERVER)%'
            options:
                username: '%env(resolve:MONGODB_USERNAME)%'
                password: '%env(resolve:MONGODB_PASSWORD)%'
                db: '%env(resolve:MONGO_INITDB_DATABASE)%'
    default_database: '%env(resolve:MONGO_INITDB_DATABASE)%'
    document_managers:
        default:
            auto_mapping: true

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    url: '%env(resolve:MAILER_URL)%'
    spool: { type: 'memory' }

#FOSUserBundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Wealthbot\UserBundle\Entity\User
    group:
        group_class: Wealthbot\UserBundle\Entity\Group
    from_email:
        address: noreply@wealthbot.io
        sender_name: 'Wealthbot.io'
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: WealthbotAdminBundle::_pagination.html.twig     # sliding pagination controls template
        sortable: WealthbotAdminBundle::_pagination_sortable.html.twig

knp_snappy:
    pdf:
        enabled:    true
        #WIN
        #CentOS
        binary:     %wkhtmltopdf_path%
        options:    []


jms_serializer:
    metadata:
        debug: %kernel.debug%
        auto_detection: true

#    property_naming:
#        separator:
#        lower_case: false
nelmio_api_doc: ~

parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
    locale: en
    secret: 'EA155B775CYU8E27997E385A5E4F8349SECRET'
    site_domain: 'wealthbot.localhost'
    pager_per_page: 20
    uploads_dir: '%kernel.root_dir%/../uploads'
    uploads_ria_company_logos_dir: '%uploads_dir%/ria_company_logos'
    uploads_documents_dir: '%uploads_dir%/documents'
    uploads_trade_files_dir: '%uploads_dir%/trade_files'
    active_jobs_dir: '%kernel.root_dir%/../system/incoming_files/active_jobs'
    docusign_username: 14d3fac4-ea15-46e9-95f8-96c84c3c8b51
    docusign_password: pass4wealthbot
    docusign_integrator_key: ROOW-10ed1300-2a9d-4169-b30c-f2849d8be519
    docusign_personal_account: EA155B06-5CAD-4E27-997E-385A5E4F8349
    docusign_ira_account: 0DE8E1BB-F301-4D0A-92A9-DCEBB78203AE
    docusign_electronic_funds_transfer_form: 10817A22-6DCF-4CAE-B379-AF4B7DF54047
    docusign_account_transfer_form: 60E63BD4-6047-448C-B390-D8EC734B94C1
    docusign_check_request: BBD7E655-E694-4D77-A5AA-833714A2FD7B
    docusign_wire_instructions: 19C426B5-ACAB-46B0-9EF6-963DA60CD8CF
    docusign_ira_distribution_form: 907D8593-315D-4F67-8224-4B649B8AD4BD
    docusign_beneficiary_designation_form: CC91DE97-A57B-4BED-BD33-5B5F3FDF530F
    docusign_brand_id: bd5bd28d-c8f3-4760-b70c-2be64e67ebf4
    wkhtmltopdf_path: /opt/wkhtmltopdf/bin/wkhtmltopdf