parameters:
    db_url: 'mysql://root:root@wealthbot_db_1:3306/wealthbot'
    mongo_user: 'webo'
    mongo_password: 'password'
    mongo_db: 'wealthbot'
    mailer_url: 'null://localhost'
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
    locale: en
    secret: 'EA155B775CYU8E27997E385A5E4F8349SECRET'
    site_domain: 'localhost'
    pager_per_page: 20
    uploads_dir: '%kernel.root_dir%/../uploads'
    uploads_ria_company_logos_dir: '%uploads_dir%/ria_company_logos'
    uploads_documents_dir: '%uploads_dir%/documents'
    uploads_trade_files_dir: '%uploads_dir%/trade_files'
    active_jobs_dir: '%kernel.root_dir%/../system/incoming_files/active_jobs'
    docusign_username: 14d3fac4-ea15-46e9-95f8-96c84c3c8b51
    docusign_password: pass4wealthbot
    docusign_integrator_key: ROOW-10ed1300-2a9d-4169-b30c-f2849d8be519
    docusign_personal_account: EA155B06-5CAD-4E27-997E-385A5E4F8349
    docusign_ira_account: 0DE8E1BB-F301-4D0A-92A9-DCEBB78203AE
    docusign_electronic_funds_transfer_form: 10817A22-6DCF-4CAE-B379-AF4B7DF54047
    docusign_account_transfer_form: 60E63BD4-6047-448C-B390-D8EC734B94C1
    docusign_check_request: BBD7E655-E694-4D77-A5AA-833714A2FD7B
    docusign_wire_instructions: 19C426B5-ACAB-46B0-9EF6-963DA60CD8CF
    docusign_ira_distribution_form: 907D8593-315D-4F67-8224-4B649B8AD4BD
    docusign_beneficiary_designation_form: CC91DE97-A57B-4BED-BD33-5B5F3FDF530F
    docusign_brand_id: bd5bd28d-c8f3-4760-b70c-2be64e67ebf4
    wkhtmltopdf_path: /opt/wkhtmltopdf/bin/wkhtmltopdf
