Wealthbot\UserBundle\Entity\Profile:
    properties:
        estimated_income_tax:
            - Min: 0
            - Max: 100
Wealthbot\UserBundle\Entity\User:
    constraints:
        - Callback:
            methods: [isPasswordLegal]
            groups: [password]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
Wealthbot\UserBundle\Entity\Group:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, owner]
