version: 1.1.x.{build}
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
- SET
- 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
environment:
  matrix:
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 21
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 21-x64
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 23
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 23-x64
matrix:
  fast_finish: true
install:
- SET PATH=C:\Ruby%RUBY_VER%\bin;%PATH%
- ps: |
    # AppVeyor appears to have OpenSSL headers available already
    # which msys2 would normally install with:
    # pacman -S mingw-w64-x86_64-openssl --noconfirm
    #
    if ( $(ruby --version) -match "^ruby\s+2\.4" ) {
      Write-Output "Building OpenSSL gem ~> 2.0.4 to fix Ruby 2.4 / AppVeyor issue"
      gem install openssl --version '~> 2.0.4' --no-ri --no-rdoc
    }

    gem list openssl
    ruby -ropenssl -e 'puts \"OpenSSL Version - #{OpenSSL::OPENSSL_VERSION}\"; puts \"OpenSSL Library Version - #{OpenSSL::OPENSSL_LIBRARY_VERSION}\"'
- bundle install --jobs 4 --retry 2 --without system_tests
- type Gemfile.lock
build: off
test_script:
- bundle exec puppet -V
- ruby -v
- bundle exec rake spec SPEC_OPTS='--format documentation'
notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
